-- Pay-to-connect: rozmowy 1:1 zakotwiczone w wspólnym cytacie (stub płatności).
-- Uruchom po supabase-matches.sql.

CREATE TABLE IF NOT EXISTS public.conversations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  initiator_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  recipient_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  anchor_quote_id bigint NOT NULL REFERENCES public.quotes (id) ON DELETE RESTRICT,
  anchor_glosa text,
  payment_status text NOT NULL DEFAULT 'pending'
    CHECK (payment_status IN ('pending', 'stub_unlocked', 'paid')),
  created_at timestamptz NOT NULL DEFAULT now(),
  unlocked_at timestamptz,
  CONSTRAINT conversations_distinct_users CHECK (initiator_id <> recipient_id),
  CONSTRAINT conversations_unique_pair UNIQUE (initiator_id, recipient_id)
);

CREATE INDEX IF NOT EXISTS conversations_initiator_idx
  ON public.conversations (initiator_id, created_at DESC);

CREATE INDEX IF NOT EXISTS conversations_recipient_idx
  ON public.conversations (recipient_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.conversation_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id uuid NOT NULL REFERENCES public.conversations (id) ON DELETE CASCADE,
  sender_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  body text NOT NULL CHECK (char_length(trim(body)) > 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS conversation_messages_conversation_idx
  ON public.conversation_messages (conversation_id, created_at ASC);

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS conversations_select ON public.conversations;
CREATE POLICY conversations_select ON public.conversations
  FOR SELECT
  USING (auth.uid() IN (initiator_id, recipient_id));

DROP POLICY IF EXISTS conversation_messages_select ON public.conversation_messages;
CREATE POLICY conversation_messages_select ON public.conversation_messages
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.conversations c
      WHERE c.id = conversation_id
        AND auth.uid() IN (c.initiator_id, c.recipient_id)
        AND c.payment_status IN ('stub_unlocked', 'paid')
    )
  );

DROP POLICY IF EXISTS conversation_messages_insert ON public.conversation_messages;
CREATE POLICY conversation_messages_insert ON public.conversation_messages
  FOR INSERT
  WITH CHECK (
    sender_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.conversations c
      WHERE c.id = conversation_id
        AND auth.uid() IN (c.initiator_id, c.recipient_id)
        AND c.payment_status IN ('stub_unlocked', 'paid')
    )
  );

CREATE OR REPLACE FUNCTION public.create_conversation(
  p_recipient_id uuid,
  p_quote_id bigint,
  p_anchor_glosa text DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid uuid := auth.uid();
  conv_id uuid;
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'Wymagane logowanie.';
  END IF;

  IF p_recipient_id IS NULL OR p_recipient_id = uid THEN
    RAISE EXCEPTION 'Nieprawidłowy odbiorca.';
  END IF;

  IF p_quote_id IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.quotes q WHERE q.id = p_quote_id
  ) THEN
    RAISE EXCEPTION 'Cytat musi pochodzić z korpusu quotes.';
  END IF;

  INSERT INTO public.conversations (
    initiator_id,
    recipient_id,
    anchor_quote_id,
    anchor_glosa,
    payment_status
  )
  VALUES (
    uid,
    p_recipient_id,
    p_quote_id,
    NULLIF(trim(p_anchor_glosa), ''),
    'pending'
  )
  ON CONFLICT (initiator_id, recipient_id)
  DO UPDATE SET
    anchor_quote_id = EXCLUDED.anchor_quote_id,
    anchor_glosa = EXCLUDED.anchor_glosa
  RETURNING id INTO conv_id;

  RETURN conv_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.stub_unlock_conversation(p_conversation_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid uuid := auth.uid();
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'Wymagane logowanie.';
  END IF;

  UPDATE public.conversations c
  SET
    payment_status = 'stub_unlocked',
    unlocked_at = COALESCE(c.unlocked_at, now())
  WHERE c.id = p_conversation_id
    AND c.initiator_id = uid
    AND c.payment_status = 'pending';

  RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_conversation_thread(p_conversation_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid uuid := auth.uid();
  row public.conversations;
  quote_row public.quotes;
  messages jsonb;
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'Wymagane logowanie.';
  END IF;

  SELECT * INTO row
  FROM public.conversations c
  WHERE c.id = p_conversation_id
    AND uid IN (c.initiator_id, c.recipient_id);

  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  SELECT * INTO quote_row
  FROM public.quotes q
  WHERE q.id = row.anchor_quote_id;

  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'id', m.id,
        'sender_id', m.sender_id,
        'body', m.body,
        'created_at', m.created_at
      )
      ORDER BY m.created_at ASC
    ),
    '[]'::jsonb
  )
  INTO messages
  FROM public.conversation_messages m
  WHERE m.conversation_id = p_conversation_id
    AND row.payment_status IN ('stub_unlocked', 'paid');

  RETURN jsonb_build_object(
    'id', row.id,
    'initiator_id', row.initiator_id,
    'recipient_id', row.recipient_id,
    'payment_status', row.payment_status,
    'anchor_quote_id', row.anchor_quote_id,
    'anchor_glosa', row.anchor_glosa,
    'quote_text', quote_row.text,
    'quote_author', quote_row.author,
    'quote_work', quote_row.work,
    'messages', messages
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.send_conversation_message(
  p_conversation_id uuid,
  p_body text
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid uuid := auth.uid();
  msg_id bigint;
  trimmed text := trim(p_body);
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'Wymagane logowanie.';
  END IF;

  IF trimmed IS NULL OR char_length(trimmed) = 0 THEN
    RAISE EXCEPTION 'Wiadomość nie może być pusta.';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.conversations c
    WHERE c.id = p_conversation_id
      AND uid IN (c.initiator_id, c.recipient_id)
      AND c.payment_status IN ('stub_unlocked', 'paid')
  ) THEN
    RAISE EXCEPTION 'Rozmowa nie jest odblokowana.';
  END IF;

  INSERT INTO public.conversation_messages (conversation_id, sender_id, body)
  VALUES (p_conversation_id, uid, trimmed)
  RETURNING id INTO msg_id;

  RETURN msg_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.create_conversation(uuid, bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.stub_unlock_conversation(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_conversation_thread(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.send_conversation_message(uuid, text) TO authenticated;
